import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "public/sw.js",
    "next-env.d.ts",
    // Generated by @serwist/next from src/sw.ts at build time. Minified
    // single-line output; linting it produces noise, not signal.
    "public/sw.js",
  ]),
]);

export default eslintConfig;
