import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    ".next-cap/**",
    "out/**",
    "build/**",
    "public/sw.js",
    "next-env.d.ts",
    // `npx cap sync` copies the whole exported web bundle in here. It is build
    // output, not source, and it is gitignored — so a fresh CI checkout never
    // sees it, but any run that syncs before linting would drown in thousands
    // of warnings from minified chunks.
    "ios/App/App/public/**",
    // Generated by @serwist/next from src/sw.ts at build time. Minified
    // single-line output; linting it produces noise, not signal.
    "public/sw.js",
    // Transient adversarial-review agent workspaces (see .gitignore): never
    // app code, and never allowed to fail a lint run mid-swarm.
    "src/__probe-*/**",
    "src/__verify-*/**",
    "src/__refute-*/**",
  ]),
]);

export default eslintConfig;
