"use client";
import { useMemo, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { SeverityBadge } from "@/components/safety/severity-badge";
import { DISCLAIMER, alptruthChecklist, avalancheAssessment, avalancheDangerScale, avalancheGearCheck, beaconSearchPhases, companionRescueTimeline, slopeAnglesFromProfile, type AvalancheDanger } from "@/lib/safety/avalanche";
export function AvalancheSection({ elevationProfile }: { elevationProfile?: Array<{ distanceMeters: number; elevation: number }> }) {
 const [danger,setDanger]=useState<AvalancheDanger>("low"); const [yes,setYes]=useState<string[]>([]); const steep=useMemo(()=>elevationProfile?slopeAnglesFromProfile(elevationProfile):null,[elevationProfile]); const assessment=avalancheAssessment({danger,alptruthYesCount:yes.length,maxSlopeAngleDeg:steep?.maxAngleDeg}); const chosen=avalancheDangerScale().find((entry)=>entry.level===danger);
 const toggle=(factor:string)=>setYes((current)=>current.includes(factor)?current.filter((value)=>value!==factor):[...current,factor]);
 return <Card size="sm"><CardHeader><CardTitle>Avalanche terrain</CardTitle></CardHeader><CardContent className="space-y-3 text-xs"><div><Label htmlFor="avalanche-danger">Local danger scale</Label><Select value={danger} onValueChange={(value)=>setDanger(value as AvalancheDanger)}><SelectTrigger id="avalanche-danger"><SelectValue /></SelectTrigger><SelectContent>{avalancheDangerScale().map((entry)=><SelectItem key={entry.level} value={entry.level}>{entry.level}</SelectItem>)}</SelectContent></Select>{chosen&&<p className="mt-1 text-muted-foreground">{chosen.likelihood} {chosen.travelAdvice}</p>}</div><Separator />
 <div className="space-y-2"><p className="font-medium">ALPTRUTh checklist — {yes.length}/7 yes</p>{alptruthChecklist().map((factor)=><div key={factor.factor} className="flex items-start gap-1"><input id={`avalanche-${factor.letter}-${factor.factor}`} type="checkbox" checked={yes.includes(factor.factor)} onChange={()=>toggle(factor.factor)} /><Label className="leading-tight" htmlFor={`avalanche-${factor.letter}-${factor.factor}`}>{factor.letter} — {factor.question}</Label></div>)}</div>
 {assessment&&<div className="rounded border p-2"><SeverityBadge severity={assessment.severity}/><p className="mt-1 font-medium">Assessment: {assessment.goNoGo.toUpperCase()}</p>{steep&&<p>Steepest sustained along-track gradient: {steep.maxAngleDeg}° at {Math.round(steep.atMeters)} m.</p>}<ul className="list-disc pl-4 text-muted-foreground">{[...assessment.reasons,...assessment.actions].map((line)=><li key={line}>{line}</li>)}</ul></div>}
 <details><summary className="cursor-pointer font-medium text-foreground">Companion rescue timeline and beacon phases</summary><div className="mt-2 space-y-2"><p className="font-medium">Timeline</p>{companionRescueTimeline().map((entry)=><div key={entry.minutes} className="rounded border p-2"><p className="font-medium">{entry.minutes}: {entry.survival}</p><p className="text-muted-foreground">{entry.action}</p></div>)}<p className="font-medium">Beacon search</p><ol className="space-y-1 text-muted-foreground">{beaconSearchPhases().map((entry)=><li key={entry.phase}><strong className="text-foreground">{entry.phase}:</strong> {entry.goal} {entry.technique}</li>)}</ol></div></details>
 <details><summary className="cursor-pointer font-medium text-foreground">Gear check</summary><ul className="mt-2 list-disc pl-4 text-muted-foreground">{avalancheGearCheck().map((line)=><li key={line}>{line}</li>)}</ul></details><p className="text-[10px] text-muted-foreground">{DISCLAIMER}</p></CardContent></Card>;
}
