"use client";
import { useMemo, useState } from "react";
import { Copy } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { SeverityBadge } from "@/components/safety/severity-badge";
import { DISCLAIMER, checkInSchedule, emergencyChannels, formatPacePlan, pacePlan, pacePlanTemplate, plbActivationSteps, radioHorizonKm, radioServices, rangeAdvice } from "@/lib/safety/comms";
export function CommsSection({ altitudeM }: { altitudeM?: number }) { const template=pacePlanTemplate(); const [my,setMy]=useState(altitudeM == null ? "" : String(Math.round(altitudeM)));const [their,setTheir]=useState("");const [blocked,setBlocked]=useState(false);const [primary,setPrimary]=useState(template.primary);const [alternate,setAlternate]=useState(template.alternate);const [contingency,setContingency]=useState(template.contingency);const [emergency,setEmergency]=useState(template.emergency);const [departure,setDeparture]=useState("");const [returnAt,setReturnAt]=useState("");const [interval,setInterval]=useState("4"); const height=parseFloat(my); const horizon=radioHorizonKm(height);const advice=rangeAdvice({myElevationM:height,theirElevationM:parseFloat(their),terrainBlocked:blocked}); const pace=formatPacePlan(pacePlan({primary,alternate,contingency,emergency}));const schedule=useMemo(()=>checkInSchedule({departureIso:departure,expectedReturnIso:returnAt,intervalHours:parseFloat(interval)}),[departure,returnAt,interval]);
 return <Card size="sm"><CardHeader><CardTitle>Communications plan</CardTitle></CardHeader><CardContent className="space-y-3 text-xs"><div className="grid grid-cols-2 gap-2"><div><Label htmlFor="comms-my">Your site height (m)</Label><Input id="comms-my" type="number" value={my} onChange={e=>setMy(e.target.value)}/></div><div><Label htmlFor="comms-their">Other site height (m)</Label><Input id="comms-their" type="number" value={their} onChange={e=>setTheir(e.target.value)}/></div></div><div className="flex items-center gap-1"><input id="comms-blocked" type="checkbox" checked={blocked} onChange={e=>setBlocked(e.target.checked)}/><Label htmlFor="comms-blocked">Terrain blocks the path</Label></div>{horizon!=null&&<p>One-station geometric horizon: approximately <strong>{horizon} km</strong>.</p>}<div className="rounded border p-2"><SeverityBadge severity={advice.severity}/><p className="mt-1">{advice.message}</p></div>
 <details><summary className="cursor-pointer font-medium text-foreground">Radio services and emergency channels</summary><div className="mt-2 space-y-2 overflow-x-auto"><table className="w-full text-left text-[10px]"><thead><tr className="border-b"><th>Service</th><th>Band / licence</th><th>Range</th></tr></thead><tbody>{radioServices().map(row=><tr key={row.service} className="border-b align-top"><td>{row.service}</td><td>{row.band}<br/>{row.licence}</td><td>{row.typicalRangeKm}</td></tr>)}</tbody></table><ul className="list-disc pl-4 text-muted-foreground">{emergencyChannels().map(row=><li key={row.channel}><strong className="text-foreground">{row.channel}:</strong> {row.use}</li>)}</ul></div></details>
 <details><summary className="cursor-pointer font-medium text-foreground">PACE plan</summary><div className="mt-2 space-y-2">{([["comms-primary","Primary",primary,setPrimary],["comms-alternate","Alternate",alternate,setAlternate],["comms-contingency","Contingency",contingency,setContingency],["comms-emergency","Emergency",emergency,setEmergency]] as const).map(([id,label,value,setter])=><div key={id}><Label htmlFor={id}>{label}</Label><Input id={id} value={value} onChange={e=>setter(e.target.value)}/></div>)}<pre className="whitespace-pre-wrap rounded bg-muted p-2 text-[10px]">{pace}</pre><Button size="sm" variant="outline" onClick={()=>void navigator.clipboard?.writeText(pace)}><Copy className="size-3"/> Copy PACE plan</Button></div></details>
 <details><summary className="cursor-pointer font-medium text-foreground">PLB and check-in schedule</summary><div className="mt-2 space-y-2"><ul className="list-disc pl-4 text-muted-foreground">{plbActivationSteps().map(line=><li key={line}>{line}</li>)}</ul><div className="grid grid-cols-2 gap-2"><div><Label htmlFor="comms-departure">Departure</Label><Input id="comms-departure" type="datetime-local" value={departure} onChange={e=>setDeparture(e.target.value)}/></div><div><Label htmlFor="comms-return">Expected return</Label><Input id="comms-return" type="datetime-local" value={returnAt} onChange={e=>setReturnAt(e.target.value)}/></div></div><Label htmlFor="comms-interval">Check-in interval (hours)</Label><Input id="comms-interval" type="number" value={interval} onChange={e=>setInterval(e.target.value)}/>{schedule&&<ul className="list-disc pl-4 text-muted-foreground">{schedule.map(time=><li key={time}>{new Date(time).toLocaleString()}</li>)}</ul>}</div></details><p className="text-[10px] text-muted-foreground">{DISCLAIMER}</p></CardContent></Card>;
}
