"use client";
import { useMemo, useState } from "react";
import { Copy } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { SeverityBadge } from "@/components/safety/severity-badge";
import { DISCLAIMER, TERRAIN_FACTORS, formatLoadPlan, loadPlan, packWeightAdvice, tenEssentials, type TerrainFactor } from "@/lib/safety/load";
export function LoadSection() {
 const [body,setBody]=useState("");const [base,setBase]=useState("");const [hours,setHours]=useState("");const [distance,setDistance]=useState("");const [speed,setSpeed]=useState("");const [grade,setGrade]=useState("");const [terrain,setTerrain]=useState<TerrainFactor>("dirt-road"); const plan=useMemo(()=>loadPlan({bodyMassKg:parseFloat(body),baseWeightKg:parseFloat(base),hours:parseFloat(hours),distanceM:parseFloat(distance)*1000,speedMs:parseFloat(speed),gradePct:parseFloat(grade),terrain,workRate:"moderate"}),[body,base,hours,distance,speed,grade,terrain]); const verdict=packWeightAdvice({bodyMassKg:parseFloat(body),packKg:parseFloat(base)}); const text=plan?formatLoadPlan(plan):"";
 const fields=[["load-body","Body mass (kg)",body,setBody],["load-base","Base weight (kg)",base,setBase],["load-hours","Hours",hours,setHours],["load-distance","Distance (km)",distance,setDistance],["load-speed","Speed (m/s)",speed,setSpeed],["load-grade","Grade (%)",grade,setGrade]] as const;
 return <Card size="sm"><CardHeader><CardTitle>Load and pack plan</CardTitle></CardHeader><CardContent className="space-y-3 text-xs"><div className="grid grid-cols-2 gap-2">{fields.map(([id,label,value,setter])=><div key={id}><Label htmlFor={id}>{label}</Label><Input id={id} type="number" value={value} onChange={e=>setter(e.target.value)}/></div>)}<div><Label htmlFor="load-terrain">Terrain</Label><Select value={terrain} onValueChange={v=>setTerrain(v as TerrainFactor)}><SelectTrigger id="load-terrain"><SelectValue/></SelectTrigger><SelectContent>{Object.keys(TERRAIN_FACTORS).map(value=><SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div></div>
 {plan&&<div className="rounded border p-2"><p>Total pack: <strong>{plan.totalPackKg} kg</strong> · water {plan.water.liters} L ({plan.water.waterKg} kg) · food {plan.calories.kcal.toFixed(0)} kcal ({plan.calories.foodKg} kg)</p><p>March estimate: {plan.march.minutes.toFixed(0)} min at {plan.march.kph} km/h.</p><div className="mt-1"><SeverityBadge severity={plan.packAdvice.severity}/><p className="text-muted-foreground">{plan.packAdvice.message}</p></div><Button className="mt-2" size="sm" variant="outline" onClick={()=>void navigator.clipboard?.writeText(text)}><Copy className="size-3"/> Copy load plan</Button></div>}
 {!plan&&verdict&&<div className="rounded border p-2"><SeverityBadge severity={verdict.severity}/><p className="mt-1">Pack weight: {verdict.percentBodyweight}% body weight. {verdict.message}</p><p className="mt-1 text-muted-foreground">No energy estimate: that speed, grade, and terrain combination is outside the range the load equation can answer for. Reduce the pace or pick a lighter terrain to get a plan.</p></div>}
 <details><summary className="cursor-pointer font-medium text-foreground">Ten Essentials checklist</summary><div className="mt-2 space-y-2">{tenEssentials().map(entry=><div key={entry.item} className="flex gap-2"><input id={`essential-${entry.item}`} type="checkbox"/><Label htmlFor={`essential-${entry.item}`}><strong>{entry.item}:</strong> <span className="text-muted-foreground">{entry.why}</span></Label></div>)}</div></details><p className="text-[10px] text-muted-foreground">{DISCLAIMER}</p></CardContent></Card>;
}
