"use client";
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { SeverityBadge } from "@/components/safety/severity-badge";
import { DISCLAIMER, estimateWbgtC, frostbiteMinutes, heatCategory, heatIllnessTriage, hypothermiaStage, layeringAdvice, workRestCycle, type WorkRate } from "@/lib/safety/thermal";
type Exposure = "unknown" | "cold" | "heat";

export function ThermalSection() {
 const [temp,setTemp]=useState("");const [rh,setRh]=useState("");const [wind,setWind]=useState("");const [sun,setSun]=useState(true);const [wet,setWet]=useState(false);const [rate,setRate]=useState<WorkRate>("moderate");const [shiver,setShiver]=useState(false);const [exposure,setExposure]=useState<Exposure>("unknown");const [altered,setAltered]=useState(false);const [conscious,setConscious]=useState(true);const [sweating,setSweating]=useState(false);const [cramps,setCramps]=useState(false);
 const t=parseFloat(temp), h=parseFloat(rh), w=parseFloat(wind); const wbgt=estimateWbgtC({tempC:t,rhPct:h,inSun:sun}); const category=wbgt==null?null:heatCategory(wbgt);const cycle=wbgt==null?null:workRestCycle(wbgt,rate); const frost=frostbiteMinutes(t,w);const coldExposed=exposure==="cold";const heatExposed=exposure==="heat";
 // Only the aid matching the stated exposure is computed, let alone rendered.
 // These two give opposite instructions — insulate versus immerse in cold water
 // — and they used to render side by side, both badged, from one shared
 // "Altered mental status" checkbox with no exposure asked for at all.
 const hypo=coldExposed?hypothermiaStage({shivering:shiver,alteredMental:altered,conscious,coldExposed:true}):null;
 const heat=heatExposed?heatIllnessTriage({alteredMental:altered,sweating,crampsOnly:cramps,heatExposed:true}):null;const layers=layeringAdvice(t,w,wet);
 return <Card size="sm"><CardHeader><CardTitle>Thermal stress</CardTitle></CardHeader><CardContent className="space-y-3 text-xs"><div className="grid grid-cols-3 gap-2"><div><Label htmlFor="thermal-temp">Air temp (°C)</Label><Input id="thermal-temp" type="number" value={temp} onChange={e=>setTemp(e.target.value)}/></div><div><Label htmlFor="thermal-rh">Humidity (%)</Label><Input id="thermal-rh" type="number" value={rh} onChange={e=>setRh(e.target.value)}/></div><div><Label htmlFor="thermal-wind">Wind (km/h)</Label><Input id="thermal-wind" type="number" value={wind} onChange={e=>setWind(e.target.value)}/></div></div><div className="flex gap-3">{[["thermal-sun","In sun",sun,setSun],["thermal-wet","Wet layers",wet,setWet]].map(([id,label,checked,setter])=><div key={String(id)} className="flex items-center gap-1"><input id={String(id)} type="checkbox" checked={Boolean(checked)} onChange={e=>(setter as (v:boolean)=>void)(e.target.checked)}/><Label htmlFor={String(id)}>{String(label)}</Label></div>)}</div>
 <div><Label htmlFor="thermal-work">Work rate</Label><Select value={rate} onValueChange={v=>setRate(v as WorkRate)}><SelectTrigger id="thermal-work"><SelectValue/></SelectTrigger><SelectContent>{["easy","moderate","hard"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div>{wbgt!=null&&category&&cycle&&<div className="rounded border p-2"><p>Estimated WBGT: <strong>{wbgt} °C</strong> · Heat category {category.category} ({category.flag})</p><p>Work/rest: <strong>{cycle.workMinutes === "continuous" ? "continuous" : `${cycle.workMinutes} min work`}</strong> / {cycle.restMinutes} min rest · water {cycle.waterLitersPerHour} L/h</p><p className="text-muted-foreground">{cycle.note}</p></div>}{frost!=null&&<p className="rounded border border-amber-500/50 p-2">Exposed-skin frostbite time: approximately <strong>{frost} min or less</strong>.</p>}
 <details><summary className="cursor-pointer font-medium text-foreground">Hypothermia and heat illness triage</summary><div className="mt-2 space-y-2"><div><Label htmlFor="thermal-exposure">Exposure (required — the two aids treat opposite problems)</Label><Select value={exposure} onValueChange={v=>setExposure(v as Exposure)}><SelectTrigger id="thermal-exposure"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="unknown">Not stated</SelectItem><SelectItem value="cold">Cold / wet / wind exposed</SelectItem><SelectItem value="heat">Hot / high exertion in heat</SelectItem></SelectContent></Select></div><div className="flex flex-wrap gap-3">{[["thermal-shiver","Shivering",shiver,setShiver],["thermal-altered","Altered mental status",altered,setAltered],["thermal-conscious","Conscious",conscious,setConscious],["thermal-sweat","Sweating",sweating,setSweating],["thermal-cramps","Cramps only",cramps,setCramps]].map(([id,label,checked,setter])=><div key={String(id)} className="flex items-center gap-1"><input id={String(id)} type="checkbox" checked={Boolean(checked)} onChange={e=>(setter as (v:boolean)=>void)(e.target.checked)}/><Label htmlFor={String(id)}>{String(label)}</Label></div>)}</div>{exposure==="unknown"
 ?<p className="rounded border border-amber-500/50 p-2">Choose cold or heat exposure above. Hypothermia and heat illness need <strong>opposite</strong> treatment — insulating a heat-stroke patient, or dousing a hypothermic one, makes things worse — so this aid will not guess.</p>
 :(()=>{const r=hypo??heat;const title=hypo?`Hypothermia: ${hypo.stage}`:`Heat illness: ${heat?.condition}`;return r?<div className="rounded border p-2"><SeverityBadge severity={r.severity}/><p className="mt-1 font-medium">{title}</p><ul className="list-disc pl-4 text-muted-foreground">{r.actions.map(line=><li key={line}>{line}</li>)}</ul></div>:null})()}</div></details>
 <details><summary className="cursor-pointer font-medium text-foreground">Layering advice</summary>{layers&&<ul className="mt-2 list-disc pl-4 text-muted-foreground">{layers.map(line=><li key={line}>{line}</li>)}</ul>}</details><p className="text-[10px] text-muted-foreground">{DISCLAIMER}</p></CardContent></Card>;
}
